"""Python port of Jin Jing's ``main_getImage.m``.

Generates one contest-style PNG (Figure 1 of the paper) from one EEG segment:

  * Right pane: 10 s of EEG in longitudinal-bipolar montage (18 derivations
    + EKG), bandpass 0.5-40 Hz with a 60 Hz notch. The displayed window is
    the central 10 s of the 50 s recording in the source .mat file.
  * Left pane: four 10-minute regional-average spectrograms (LL, RL, LP, RP)
    on a dB color scale, with a vertical red marker indicating the time
    centre of the EEG window.

Inputs
------
The function reads from either:

  (a) one of Jin's per-segment ``.mat`` files (with ``data_50sec`` and
      ``spec_10min`` variables) — same input as the original MATLAB code; or
  (b) one segment group inside the bundled ``iiic_contest_eeg.h5`` archive.

The MATLAB reference is preserved verbatim in ``main_getImage.m`` alongside
this file. A sample PNG generated by Jin's MATLAB on the same segment is
saved as ``sample_reference.png`` for visual cross-check.

Usage
-----
$ python scripts/contest_image_gen/make_contest_image.py \\
    --segment-id pat0002_20161004_141027_5167 \\
    --mat-dir /path/to/ImageCode_JJ/Data \\
    --out figures/contest_image_pat0002.png

or, against the bundled HDF5:

$ python scripts/contest_image_gen/make_contest_image.py \\
    --segment-id pat0002_20161004_141027_5167 \\
    --h5 data/iiic_contest_eeg.h5 \\
    --out figures/contest_image_pat0002.png
"""
from __future__ import annotations

import argparse
import re
from datetime import datetime, timedelta
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import scipy.io as sio
from scipy.signal import butter, filtfilt


# ---------------------------------------------------------------------------
# Constants (match Jin's MATLAB exactly)
# ---------------------------------------------------------------------------
FS = 200                          # sampling rate (Hz)
TC = 25                           # time centre of EEG window (s) within 50 s segment
W  = 10                           # EEG window width (s)
Z_SCALE = 1 / 150                 # display scaling for EEG traces
SPEC_DB_RANGE = (-10, 25)         # spectrogram color limits
SPEC_WIN_MIN = 10                 # spectrogram window length (min)

# 1-indexed monopolar channel order matching the .mat ``data_50sec`` rows.
# Standard 19-electrode 10-20 layout (rows 1-19), EKG (row 20), Photic (row 21).
CHANNEL_ORDER = ["Fp1", "F3", "C3", "P3", "F7", "T3", "T5", "O1",
                 "Fz", "Cz", "Pz",
                 "Fp2", "F4", "C4", "P4", "F8", "T4", "T6", "O2",
                 "EKG", "Photic"]

# Longitudinal-bipolar montage (18 derivations) -- pairs of 1-indexed indices
# into CHANNEL_ORDER. Order, layout, and labels match main_getImage.m.
BIPOLAR_PAIRS = [
    ("Fp1", "F7"),  ("F7",  "T3"),  ("T3", "T5"),  ("T5", "O1"),    # 1-4
    ("Fp2", "F8"),  ("F8",  "T4"),  ("T4", "T6"),  ("T6", "O2"),    # 5-8
    ("Fp1", "F3"),  ("F3",  "C3"),  ("C3", "P3"),  ("P3", "O1"),    # 9-12
    ("Fp2", "F4"),  ("F4",  "C4"),  ("C4", "P4"),  ("P4", "O2"),    # 13-16
    ("Fz",  "Cz"),  ("Cz",  "Pz"),                                  # 17-18
]
# Channel labels as shown on the figure, in *top-to-bottom* order, with a
# blank gap between montage chains and EKG at the bottom.
DISPLAY_LABELS_TOP_TO_BOTTOM = [
    "Fp1-F7", "F7-T3", "T3-T5", "T5-O1", "",
    "Fp2-F8", "F8-T4", "T4-T6", "T6-O2", "",
    "Fp1-F3", "F3-C3", "C3-P3", "P3-O1", "",
    "Fp2-F4", "F4-C4", "C4-P4", "P4-O2", "",
    "Fz-Cz",  "Cz-Pz", "",
    "EKG",
]
SPEC_REGIONS = ["LL", "RL", "LP", "RP"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def parse_segment_time(segment_id: str) -> datetime:
    """Recover the segment's timestamp from the file stem.

    Example: ``pat0002_20161004_141027_5167`` -> 2016-10-04 14:10:27 + (2*5167+1-5) s
    """
    parts = re.findall(r"\d+", segment_id)
    if len(parts) < 4:
        return datetime(1900, 1, 1)  # unknown; just used for axis labels
    date_str, time_str = parts[-3], parts[-2]
    offset_units = int(parts[-1])
    base = datetime.strptime(date_str + time_str, "%Y%m%d%H%M%S")
    return base + timedelta(seconds=2 * offset_units + 1 - 5)


def filter_eeg(seg: np.ndarray, fs: int = FS) -> np.ndarray:
    """0.5-40 Hz bandpass + 58-62 Hz notch (matches main_getImage.m)."""
    seg = np.nan_to_num(seg, nan=0.0)
    b1, a1 = butter(3, [0.5, 40], btype="band", fs=fs)
    b2, a2 = butter(3, [60 - 2.5, 60 + 2.5], btype="bandstop", fs=fs)
    seg = filtfilt(b1, a1, seg, axis=-1)
    seg = filtfilt(b2, a2, seg, axis=-1)
    return seg


def bipolar_montage(eeg: np.ndarray) -> np.ndarray:
    """Compute the 18-derivation longitudinal-bipolar montage.

    ``eeg`` is (19, n_samples) of monopolar channels in CHANNEL_ORDER[:19].
    Returns (18, n_samples).
    """
    idx = {name: i for i, name in enumerate(CHANNEL_ORDER[:19])}
    out = np.zeros((len(BIPOLAR_PAIRS), eeg.shape[1]), dtype=eeg.dtype)
    for k, (a, b) in enumerate(BIPOLAR_PAIRS):
        out[k] = eeg[idx[a]] - eeg[idx[b]]
    return out


def load_mat(path: Path) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    """Read one of Jin's .mat files."""
    d = sio.loadmat(str(path))
    data = d["data_50sec"]  # (21, 10000)
    specs = {str(row[0][0]): row[1] for row in d["spec_10min"]}
    return data, specs


def load_h5_segment(h5_path: Path, segment_id: str
                    ) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    """Read one segment from the bundled HDF5."""
    import h5py
    with h5py.File(h5_path, "r") as h:
        grp = h[f"segments/{segment_id}"]
        data = grp["data_50sec"][:]
        specs = {r: grp[f"spec_{r}"][:] for r in SPEC_REGIONS}
    return data, specs


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------
def plot_eeg_panel(ax, eeg_montage: np.ndarray, ekg: np.ndarray,
                   seg_time: datetime, fs: int = FS):
    """Render the 10 s EEG panel (right side of the contest image)."""
    n_chan = eeg_montage.shape[0]
    n_samples = eeg_montage.shape[1]

    # Y positions: top channel = highest y, EKG at bottom (y=1).
    rows_top_to_bottom = DISPLAY_LABELS_TOP_TO_BOTTOM
    n_rows = len(rows_top_to_bottom)

    # Map montage-derivation index -> display row index (top-to-bottom).
    eeg_label_to_row: dict[str, int] = {}
    montage_labels = ["Fp1-F7", "F7-T3", "T3-T5", "T5-O1",
                      "Fp2-F8", "F8-T4", "T4-T6", "T6-O2",
                      "Fp1-F3", "F3-C3", "C3-P3", "P3-O1",
                      "Fp2-F4", "F4-C4", "C4-P4", "P4-O2",
                      "Fz-Cz",  "Cz-Pz"]
    for k, lbl in enumerate(montage_labels):
        row_top = rows_top_to_bottom.index(lbl)
        eeg_label_to_row[lbl] = row_top
    ekg_row_top = rows_top_to_bottom.index("EKG")

    t = np.arange(n_samples) / fs

    for k, lbl in enumerate(montage_labels):
        y_offset = n_rows - eeg_label_to_row[lbl]
        ax.plot(t, Z_SCALE * eeg_montage[k] + y_offset, color="k", lw=0.5)
    # EKG: z-normalised, plotted in red.
    ekg_norm = (ekg - ekg.mean()) / (ekg.std() + 1e-9)
    ax.plot(t, 0.2 * ekg_norm + (n_rows - ekg_row_top),
            color="r", lw=0.5)

    # Vertical second-by-second grid.
    for k in range(1, int(t[-1]) + 1):
        ax.axvline(k, color="0.4", lw=0.5, ls="--")

    # Scale bar: 100 µV vertical, 1 s horizontal.
    bar_x = t[-1] - 1.5
    bar_y = 2.5
    ax.plot([bar_x, bar_x + 1], [bar_y, bar_y], color="b", lw=1.5)
    ax.plot([bar_x, bar_x], [bar_y, bar_y + 100 * Z_SCALE], color="b", lw=1.5)
    ax.text(bar_x + 0.5, bar_y - 0.25, "1 s", color="b", ha="center", fontsize=7)
    ax.text(bar_x - 0.1, bar_y + 50 * Z_SCALE, "100 µV",
            color="b", ha="right", va="center", fontsize=7)

    # Y axis: channel labels in top-to-bottom order at integer positions.
    y_ticks = [n_rows - i for i, lbl in enumerate(rows_top_to_bottom) if lbl]
    y_labels = [lbl for lbl in rows_top_to_bottom if lbl]
    ax.set_yticks(y_ticks)
    ax.set_yticklabels(y_labels, fontsize=8)
    ax.set_ylim(0.5, n_rows + 0.5)

    # X axis: time of day, one tick per second.
    tick_positions = np.arange(0, int(t[-1]) + 1)
    secs = [seg_time + timedelta(seconds=int(s)) for s in tick_positions]
    ax.set_xticks(tick_positions)
    ax.set_xticklabels([s.strftime("%H:%M:%S") for s in secs], fontsize=7,
                       rotation=0)
    ax.set_xlim(0, t[-1])
    ax.set_facecolor("white")
    for spine in ax.spines.values():
        spine.set_visible(True)


def plot_spectrogram_panel(axes, specs: dict[str, np.ndarray],
                           seg_time: datetime):
    """Render the 4 stacked spectrograms (left side of the contest image)."""
    extent_min = SPEC_WIN_MIN  # 10 minutes total
    for i, region in enumerate(SPEC_REGIONS):
        ax = axes[i]
        spec = specs[region]                          # (n_freq, n_time)
        spec_db = 10 * np.log10(np.maximum(spec, 1e-12))
        # Frequency axis is 0..20 Hz (MATLAB: S_y = 1:20).
        ax.imshow(spec_db, origin="lower", aspect="auto",
                  vmin=SPEC_DB_RANGE[0], vmax=SPEC_DB_RANGE[1],
                  cmap="jet",
                  extent=[0, extent_min, 0, 20])
        # Central marker showing the 10 s EEG window's location.
        ax.axvline(extent_min / 2, color="k", ls="--", lw=1)
        # Region label printed in the top-left of the panel (matches MATLAB
        # which overwrites the top Y-tick label with the region name).
        ax.text(0.01, 0.95, region, transform=ax.transAxes,
                fontsize=10, fontweight="bold", color="white",
                va="top", ha="left",
                bbox=dict(facecolor="black", alpha=0.6, pad=2, edgecolor="none"))
        ax.set_ylabel("Freq (Hz)", fontsize=8)
        ax.tick_params(labelsize=7)
        if i < 3:
            ax.set_xticks([])
        else:
            # Bottom panel: time-of-day labels every 2.5 minutes.
            ticks_min = np.arange(0, extent_min + 0.001, 2.5)
            tick_times = [seg_time - timedelta(minutes=extent_min / 2 - tm)
                          for tm in ticks_min]
            ax.set_xticks(ticks_min)
            ax.set_xticklabels([t.strftime("%H:%M:%S") for t in tick_times],
                               fontsize=6, rotation=0)


def plot_top_marker(fig, spec_axes):
    """Red triangle above the top spectrogram, pointing at the central time."""
    top_ax = spec_axes[0]
    # Convert data point (5 min, top-edge) to figure coordinates.
    pos = top_ax.get_position()
    cx = pos.x0 + pos.width * 0.5
    cy = pos.y0 + pos.height + 0.003
    fig.add_artist(plt.Polygon(
        [(cx - 0.006, cy + 0.012), (cx + 0.006, cy + 0.012), (cx, cy)],
        closed=True, facecolor="red", edgecolor="red"))


def render_contest_image(data_50sec: np.ndarray,
                         specs: dict[str, np.ndarray],
                         segment_id: str,
                         out_path: Path):
    """Build the contest image and write it to ``out_path``."""
    # Trim to the central 10 s window of the 50 s segment.
    t_start = (TC - W // 2) * FS
    t_end = (TC + W // 2) * FS
    eeg_full = filter_eeg(data_50sec[:, t_start:t_end].astype(np.float64))
    eeg19 = eeg_full[:19]
    ekg = -eeg_full[19]  # MATLAB code negates row 20

    eeg_montage = bipolar_montage(eeg19)
    seg_time = parse_segment_time(segment_id)

    fig = plt.figure(figsize=(16, 9), facecolor="white")
    # 4 spectrograms on the left, 1 big EEG panel on the right.
    spec_axes = [
        fig.add_axes((0.03, 0.735, 0.35, 0.225)),
        fig.add_axes((0.03, 0.500, 0.35, 0.225)),
        fig.add_axes((0.03, 0.265, 0.35, 0.225)),
        fig.add_axes((0.03, 0.030, 0.35, 0.225)),
    ]
    eeg_ax = fig.add_axes((0.415, 0.030, 0.560, 0.935))

    plot_spectrogram_panel(spec_axes, specs, seg_time)
    plot_top_marker(fig, spec_axes)
    plot_eeg_panel(eeg_ax, eeg_montage, ekg, seg_time)

    fig.savefig(out_path, dpi=120, facecolor="white", bbox_inches=None)
    plt.close(fig)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    p = argparse.ArgumentParser()
    p.add_argument("--segment-id", required=True,
                   help="Segment stem (the .mat filename without extension)")
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--mat-dir", type=Path,
                     help="Directory containing per-segment .mat files")
    src.add_argument("--h5", type=Path,
                     help="iiic_contest_eeg.h5 bundle path")
    p.add_argument("--out", type=Path, required=True,
                   help="Output PNG path")
    args = p.parse_args()

    if args.mat_dir is not None:
        data, specs = load_mat(args.mat_dir / f"{args.segment_id}.mat")
    else:
        data, specs = load_h5_segment(args.h5, args.segment_id)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    render_contest_image(data, specs, args.segment_id, args.out)
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
